[theme]
primaryColor = "#c22fcf"
backgroundColor = "#16313b"
secondaryBackgroundColor = "#25b16f"
textColor = "#c2e8eb"
linkColor = "#3d3a2a"
borderColor = "#0bf7ff"
showWidgetBorder = true
baseRadius = "0.75rem"
buttonRadius = "full"
font = "monospace"
headingFontWeights = [600,500,500,500,500,500]
headingFontSizes = ["3rem", "2rem"]
codeFont = "SpaceMono"
codeFontSize = ".75rem"
codeBackgroundColor = "#e4ebec"
showSidebarBorder = true
chartCategoricalColors = ["#0a5274", "#13a2bb", "#fbbf24"]

[theme.sidebar]
backgroundColor = "#f0f0ec"
secondaryBackgroundColor = "#ecebe3"
headingFontSizes = ["1.6rem", "1.4rem", "1.2rem"]
dataframeHeaderBackgroundColor = "#e4e4e0"